[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
name = "msp430-quickstart"
version = "0.1.0"

[dependencies.msp430]
branch = "msp430"
git = "https://github.com/japaric/cortex-m"

[dependencies.msp430-rt]
branch = "msp430-rt"
features = ["abort-on-panic"]
git = "https://github.com/japaric/cortex-m-rt"

[dependencies.msp430g2553]
branch = "regenerate"
features = ["rt"]
git = "https://github.com/japaric/msp430g2553"

[profile.release]
lto = true
