[tasks.build]
command = "cargo"
args = ["xbuild", "--example", "${@}"]

[env]
DBG_EXAMPLE_DIR = "target/msp430-none-elf/debug/examples/"

[tasks.objdump]
command = "msp430-elf-objdump"
args = ["${DBG_EXAMPLE_DIR}${@}", "-CD"]
